// pages/library/index.vue
<template>
    <h1 class="font-bold text-3xl text-center mt-5">Mechanism library</h1>
    <div class="m-auto">
        <div class="flex flex-wrap mt-16 gap-4 justify-center">
            <Card image="/thumbnails/differential.png" name="Differential"/>
        </div>
    </div>
</template>

<script setup>

</script>

<style scoped></style>

// src/routes/Library.jsx
import Card from '../components/Card.jsx'
import differential from '../assets/images/thumbnails/differential.png'

export default function Library() {
    return (
        <>
            <h1 className="font-bold text-3xl mt-36 text-center">Models library</h1>
            <div className="m-auto">
                <div className="flex flex-wrap mt-16 gap-4 justify-center">
                    <Card img={differential} name="Differential" />
                    <Card img={differential} name="Differential" />
                    <Card img={differential} name="Differential" />
                    <Card img={differential} name="Differential" />
                    <Card img={differential} name="Differential" />
                    <Card img={differential} name="Differential" />
                </div>
            </div>
        </>
    )
}
